### ISSUE TITLE
issues with 2.74

### ISSUE THREAD

**Issue by sfolden** [dfelinto/Panorama-Tracker#1]
I am trying to install this plug-in for Blender version 2.74 but it will not show up, any ideas? VERY excited to use this plug-in!!! I downloaded zip, went to plug-ins and install from file. Also tried using just the .py script rather than zip file but to no avail.

**Comment by dfelinto** [comment]
Hi, I just tried and it worked.

Use the python script (as you did):
https://raw.githubusercontent.com/dfelinto/Panorama-Tracker/master/scripts/panorama_tracker.py

Make sure to have 'Community' turned on, and search for 'Panorama Tracker' in the Add-ons panel in the User Preferences.

Once you have the addon turned on you can find its panels in the 'Misc' tab of the Movie Clip Editor Tools panel.

**Comment by sfolden** [comment]
That was it! Thank you very much for the quick reply, and for an amazing add on!

**Comment by dfelinto** [comment]
Issue closed then, let me know how useful the addon turns out to be, cheers
